### ISSUE TITLE
route 설정 이슈

### ISSUE THREAD

**Issue by rkdehdgns1230** [bnk159hair/SE_Project_3#22]
routes/mypage.js 여기서 route들 

/routes -> api/routes 로 변경해야 proxy server 매개해서 nodejs 서버랑 통신 가능합니다. 수정해야할 듯

아마 승건형 통신 안된다고 했는데, 이거 때문에 그런 것 같습니다.

**Comment by bnk159hair** [comment]
확인했습니다.

**Comment by bnk159hair** [comment]
확인했습니다.
